version: '3.9'

services:
  fail2ban:
    image: crazymax/fail2ban:latest
    container_name: fail2ban
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    env_file: .env
    volumes:
      - ./data:/data
      - /var/log/traefik:/var/log/traefik:ro
      - /var/log/vaultwarden:/var/log/vaultwarden:ro