version: '3.8'
services:
    vaultwarden:
        image: vaultwarden/server:latest
        container_name: vaultwarden
        restart: unless-stopped
        env_file: .env
        volumes:
            - vault-data:/data/
        labels:
            - traefik.enable=true
            - traefik.http.routers.vaultwarden.rule=Host(`${HOST}`)
            - traefik.http.routers.vaultwarden.entrypoints=websecure
            - traefik.http.services.vaultwarden.loadbalancer.server.port=80
volumes:
    vault-data:

networks:
    default:
        name: traefik
        external: true
