version: '3.8'
services:
    vaultwarden:
        image: vaultwarden/server:latest
        container_name: vaultwarden
        restart: unless-stopped
        env_file: .env
        environment:
            - DOMAIN=https://vault.c-bv.dev
            - SENDS_ALLOWED=true
            - EMERGENCY_ACCESS_ALLOWED=true
            - WEB_VAULT_ENABLED=true
            - SIGNUPS_ALLOWED=false
            - SIGNUPS_DOMAINS_WHITELIST=c-bv.dev
        volumes:
            - vault-data:/data/
        labels:
            - traefik.enable=true
            - traefik.http.routers.vaultwarden.rule=Host(`vault.c-bv.dev`)
            - traefik.http.routers.vaultwarden.entrypoints=websecure
            - traefik.http.services.vaultwarden.loadbalancer.server.port=80
volumes:
    vault-data:

networks:
    default:
        name: traefik
        external: true
