version: '3.8'

services:
    traefik:
        image: traefik:v2.10
        container_name: traefik
        restart: unless-stopped
        command:
            - --log.level=DEBUG
            - --api.dashboard=true
            - --providers.docker=true
            - --providers.docker.exposedbydefault=false

            # WEB
            - --entrypoints.web.address=:80
            - --entrypoints.websecure.address=:443
            - --entrypoints.web.http.redirections.entryPoint.to=websecure

            # CERT
            - --certificatesresolvers.myresolver.acme.dnschallenge=true
            - --certificatesresolvers.myresolver.acme.dnschallenge.provider=ovh
            - --certificatesresolvers.myresolver.acme.email=system@c-bv.dev
            - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
            # - --certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory$
            - --entrypoints.websecure.http.tls.certresolver=myresolver
            - --entrypoints.websecure.http.tls.domains[0].main=c-bv.dev
            - --entrypoints.websecure.http.tls.domains[0].sans=*.c-bv.dev
            
            # SMTP
            - --entrypoints.smtp.address=:25
            - --entryPoints.smtp-ssl.address=:465
            - --entryPoints.imap-ssl.address=:993
            - --entryPoints.sieve.address=:4190
        ports:
            - 80:80
            - 443:443
            - 25:25
            - 465:465
            - 993:993
            - 4190:4190
        env_file: .env
        volumes:
            - letsencrypt:/letsencrypt
            - /var/run/docker.sock:/var/run/docker.sock:ro
        labels:
            - traefik.enable=true
            - traefik.http.routers.dashboard.rule=Host(`traefik.c-bv.dev`)
            - traefik.http.routers.dashboard.service=api@internal
            - traefik.http.routers.dashboard.middlewares=auth
            - traefik.http.middlewares.auth.basicauth.users=c-bv:$$2y$$05$$bDjUP6ptjAAeK7gBc/Anfuqy5pMFOt9STunpZke5v1DA2LH2iQ85a

    whoami:
        image: traefik/whoami
        container_name: whoami
        labels:
            - traefik.enable=true
            - traefik.http.routers.whoami.rule=Host(`whoami.c-bv.dev`)
            - traefik.http.routers.whoami.middlewares=auth
            - traefik.http.middlewares.auth.basicauth.users=c-bv:$$2y$$05$$bDjUP6ptjAAeK7gBc/Anfuqy5pMFOt9STunpZke5v1DA2LH2iQ85a

volumes:
    letsencrypt:
        external: true

networks:
    default:
        name: traefik
