version: '3.8'

services:
    uptime-kuma:
        image: louislam/uptime-kuma:1
        container_name: uptime-kuma
        restart: always
        volumes:
            - uptime-kuma:/app/data
        labels:
            - traefik.enable=true
            - traefik.http.routers.uptime-kuma.rule=Host(`${HOST}`)
            - traefik.http.routers.uptime-kuma.entrypoints=websecure
            - traefik.http.services.uptime-kuma.loadbalancer.server.port=3001
            
volumes:
    uptime-kuma:

networks:
    default:
        name: traefik
        external: true
