services:
    wg-easy:
        image: ghcr.io/wg-easy/wg-easy
        container_name: wg-easy
        restart: unless-stopped
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        sysctls:
            - net.ipv4.ip_forward=1
            - net.ipv4.conf.all.src_valid_mark=1
        env_file: .env
        volumes:
            - wg_easy_data:/etc/wireguard
        labels:
            - traefik.enable=true
            - traefik.udp.routers.wg-easy.entrypoints=wireguard
            - traefik.udp.routers.wg-easy.service=wg-easy
            - traefik.udp.services.wg-easy.loadbalancer.server.port=51820
            
            - traefik.http.routers.wg-easy-ui.rule=Host(`${HOST}`)
            - traefik.http.routers.wg-easy-ui.entrypoints=websecure
            - traefik.http.services.wg-easy-ui.loadbalancer.server.port=51821
volumes:
    wg_easy_data:

networks:
    default:
        name: traefik
        external: true
