name: CI

on:
    push:
        branches: ['main']

env:
    REGISTRY: ghcr.io
    REPO_NAME: ${{ github.event.repository.name }}
    ENV_TRAEFIK: ${{ secrets.ENV_TRAEFIK }}
    ENV_MAILER: ${{ secrets.ENV_MAILER }}

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to VPS
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_KEY }}
                  port: ${{ secrets.SSH_PORT }}
                  script: |
                      cd /opt/${{ env.REPO_NAME }}
                      git pull

                      CHANGED_DIRS=$(git diff --name-only ${{ github.sha }} ${{ github.event.before }} | grep -v "^\.github/" | xargs -I {} dirname {} | uniq)
                      echo "Changed directories: $CHANGED_DIRS"

                      for DIR in $CHANGED_DIRS
                      do
                          echo "Deploying ${DIR}..."
                      
                          ENV_VAR_NAME="ENV_$(echo $DIR | tr '[:lower:]' '[:upper:]')"
                          echo "ENV_VAR_NAME: $ENV_VAR_NAME"
                      
                          ENV_FILE="${!ENV_VAR_NAME}"
                          echo "ENV_FILE: $ENV_FILE"  
                      
                          if [ -z "$ENV_FILE" ]; then
                            echo "No .env configuration for ${DIR}, skipping..."
                            continue
                          fi
                          
                          cd $DIR
                          echo $ENV_FILE | base64 -d > .env
                      
                          docker compose up -d --force-recreate
                      done
                      
