name: CI

on:
    push:
        branches: ['main']

env:
    REGISTRY: ghcr.io
    REPO_NAME: ${{ github.event.repository.name }}

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to VPS
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_KEY }}
                  port: ${{ secrets.SSH_PORT }}
                  script: |
                      cd /opt/${{ env.REPO_NAME }}
                      git pull

                      CHANGED_DIRS=$(git diff --name-only ${{ github.sha }} ${{ github.event.before }} | grep -v "^\.github/" | xargs -I {} dirname {} | uniq)
                      echo "Changed directories: $CHANGED_DIRS"

                      echo ${{ secrets.DOTENV }} > .env

                      for DIR in $CHANGED_DIRS
                      do
                          echo "Deploying ${DIR}..."
                          cd $DIR
                          docker compose up -d --force-recreate
                      done
