name: CI

on:
    push:
        branches: ['main']

env:
    REGISTRY: ghcr.io
    REPO_NAME: ${{ github.event.repository.name }}

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to VPS
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_KEY }}
                  port: ${{ secrets.SSH_PORT }}
                  script: |
                      pwd
                      cd /opt/$REPO_NAME/traefik
                      git pull
                      docker compose down --rmi all
                      docker compose up -d