version: '3.8'
services:
    dockge:
        image: louislam/dockge:1
        container_name: dockge
        restart: unless-stopped
        env_file: .env
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - dockge:/app/data
            - /opt/stacks:/opt/stacks
        labels:
            - traefik.enable=true
            - traefik.http.routers.dockge.rule=Host(`${HOST}`)
            - traefik.http.routers.dockge.entrypoints=websecure
            - traefik.http.services.dockge.loadbalancer.server.port=5001

volumes:
    dockge:

networks:
    default:
        name: traefik
        external: true
